### ISSUE TITLE
Only HTML is showing not CSS

### ISSUE THREAD

**Issue by steve-vuori** [khriztianmoreno/storybook-addon-raw-styled-component#73]
Please advise, I can't get the CSS to output.

**Comment by khriztianmoreno** [comment]
Hi @steve-vuori  You can tell me specifically that it does not work for you and give me more information on how you are doing the process, versions of the dependencies you use.

**Comment by steve-vuori** [comment]
Hi @khriztianmoreno,

Thank you for your response! I am using Storybook 6.1.17. I tried disabling all other addons and still only get the HTML to display. I have the addon installed, I have it configured like this in preview.js:

import { withHTML } from '@khriztianmoreno/storybook-addon-raw-styled-component';
addDecorator(withHTML);

No CSS appears, but HTML does. 
<img width="1709" alt="Screen Shot 2021-02-09 at 8 46 21 AM" src="https://user-images.githubusercontent.com/62361420/107397267-5b657c80-6ab3-11eb-89a0-f45e6e0ddf3e.png">

Thank you for your help!

**Comment by steve-vuori** [comment]
@khriztianmoreno 

Do you think this could be a conflict with the newest version of Storybook? Perhaps a conflict with another addon? Or does it appear anything is misconfigured? I'd love to get CSS output going for the rest of my team to review. Thank you so much!
